-- CREATE TYPE "public"."join_request_status" AS ENUM('NA_CEKANJU', 'ODBIJEN', 'PRIHVACEN');--> statement-breakpoint
-- CREATE TABLE "event_registrations" (
-- 	"event_id" integer NOT NULL,
-- 	"team_id" integer NOT NULL,
-- 	"price" numeric(10, 2) NOT NULL,
-- 	CONSTRAINT "event_registrations_event_id_team_id_pk" PRIMARY KEY("event_id","team_id")
-- );
-- --> statement-breakpoint
-- CREATE TABLE "event_results" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"event_id" integer NOT NULL,
-- 	"team_id" integer NOT NULL,
-- 	"placement" integer NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE "events" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"season_id" integer NOT NULL,
-- 	"name" varchar(150) NOT NULL,
-- 	"theme" varchar(150),
-- 	"location" varchar(150) NOT NULL,
-- 	"event_date" timestamp NOT NULL,
-- 	"capacity" integer NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE "team_join_requests" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"team_id" integer NOT NULL,
-- 	"user_id" integer NOT NULL,
-- 	"status" "join_request_status" DEFAULT 'NA_CEKANJU' NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE "team_members" (
-- 	"team_id" integer NOT NULL,
-- 	"user_id" integer NOT NULL,
-- 	CONSTRAINT "team_members_team_id_user_id_pk" PRIMARY KEY("team_id","user_id")
-- );
-- --> statement-breakpoint
-- ALTER TABLE "event_registrations" ADD CONSTRAINT "event_registrations_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "event_registrations" ADD CONSTRAINT "event_registrations_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "event_results" ADD CONSTRAINT "event_results_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "event_results" ADD CONSTRAINT "event_results_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "events" ADD CONSTRAINT "events_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "team_join_requests" ADD CONSTRAINT "team_join_requests_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "team_join_requests" ADD CONSTRAINT "team_join_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;