name: CI Pipeline

on:
  pull_request:
    branches: ["develop"] # pokreće se kad praviš PR ka develop
  push:
    branches: ["develop"] # pokreće se i kad direktno pushuješ na develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
      JWT_SECRET: test_secret

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run migrations
        run: npm run db:migrate

      - name: Seed database
        run: npm run db:seed

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Run unit/integration tests
        run: npm run test
